### ISSUE TITLE
Everything checklist

### ISSUE THREAD

**Issue by WithoutAnAccent** [A1tered/COS40005_AntiVirusProject#406]

**Comment by WithoutAnAccent** [comment]
- [ ] PDF for how to access everything
- [ ]

**Comment by WithoutAnAccent** [comment]
- [ ] Project Plan & SQAP – Revision and Execution
- [ ] Requirements Specification & System Architecture Design and Research – Revision
- [ ] Test Plan, Usability Evaluation Plan
- [ ] Testing; Test Report, Usability Evaluation Report; Quality Assurance; Version-Controlled Repository
- [ ] Detailed System Design, Implementation; System/Software Documentation; Final Product Prototype & Demonstration; Final Project Report
- [ ] Technical Documentation for Client (User Manual, Technical and Installation Manual)
- [ ] System Deployment & Delivery
- [ ] Meeting Minutes
- [ ] Final Presentation & Expo
